### ISSUE TITLE
Allow to choose font family and size

### ISSUE THREAD

**Issue by gary-host-laptop** [Darazaki/Spedread#4]
Being able to choose both of these options would be awesome in terms of accessibility and customization. Choosing the font family to one that's dyslexic friendly and using a bigger font size if you have some sight issues, for example, but still modifying this for whichever reason just because you like it more one way or another, is fine, too.

**Comment by Darazaki** [comment]
Good idea! I think that allowing to change the font for the "Read" tab makes a lot of sense. Maybe the "Text" tab too?

Also, currently the font chosen is the bold system one with a x2 scale. Should Spedread apply a x2 scale to whatever font the user chooses? This would mean that the font sizes used would be much closer to the usual ones (about 11 to 15) rather than the bigger ones (about 22 to 30) but at the same time the user wouldn't be able to see the actual size of the font until it's applied

Though obviously if the "Read" and "Text" tab both share the same font having a configurable scaling factor and bold option is going to be a must

TL;DL there are 2 main questions for now:

- Should the font in the "Text" tab also be configurable? (And independent from the "Read" tab's?)
- Should the x2 scale on the font size be kept?

**Comment by gary-host-laptop** [comment]
I think that changing the font size in the "Text" section isn't that relevant, although I would consider making it a bit bigger, but just a little bit, at least in my monitor (1400x900) it looks pretty small and although I can read it maybe other people can't.

Regarding the "Read" section, what's the point of a x2 scale? If the font has a size of 10 and you x2 scale it, it would be the same as if the font would have a font size of 20, if I'm not missing anything. So IMO I think it's the same thing, right?

**Comment by Darazaki** [comment]
You're right, I should make the font in the "Text" tab bigger

And the reason why I'm thinking about maybe keeping a x2 scale is because of people like me who can't get anything out of the GTK font picker's preview anyway and who tend to select font sizes around 13pt when guessing. Having the x2 scale would make this kind of guess correct on the 1st or 2nd try. But the issue is that, to a user, the font size they pick in the GTK font picker won't be the actual size. Meaning that the font preview won't be accurate and they may feel frustrated that what they choose isn't what's actually used

Right now I think I'd prefer ditching the x2 scaling since my personal issue doesn't sound like something most users would have but tbh I just don't know

**Comment by gary-host-laptop** [comment]
Yeah, I feel like the issue you're having affects the developer, you in this case, and not the end user. IMO since this applications is directed to end users that should be the first priority, even if it makes the programming part a bit more tedious.

**Comment by Darazaki** [comment]
Not really, it's just a question of personal taste. The programming complexity involved in removing the x2 scale should just be an if statement so I don't really care. Since it looks like it's just a "me" problem, I'll remove it

Now there should be no issue left with me implementing all of this

Thanks again for your suggestions, they're very helpful! :)

**Comment by Darazaki** [comment]
![image](https://user-images.githubusercontent.com/36732679/147842097-1a403d91-2041-43d6-86a6-3c0681357889.png)

I think I'll go for a font size of 12pt on the "Text" tab, it should work with every UI font

I've pretty much finished addressing this issue and will finish taking the updated screenshots and publish the new release tomorrow as 2.1.0 :)
