### ISSUE TITLE
No newline characters

### ISSUE THREAD

**Issue by NuSynth** [Darazaki/Spedread#6]
The words with the newline characters at the end of the strings are displayed higher than the other words. This causes me to look up quicky before the word is no longer displayed. If the newline character were treated as a space character instead, then this would alleviate the problem.

**Comment by NuSynth** [comment]
Not really sure how it's done in Vala, since I haven't worked with it in a while. But in C it would be something like:


`
    int c;

    while ((c = getchar()) != EOF)
    {
      if (c == '\n')
        printf(" ");
                      
      if (c != '\n')
        printf("%c", c);
    }
`

**Comment by Darazaki** [comment]
Thanks for telling me! I actually don't have this bug, could you tell me what font you're using? (either in Spedread if you've set it manually or else your system font)

I have a pretty good idea of how to fix that bug though so I should hopefully be able to patch it today :)

**Comment by Darazaki** [comment]
I've decided to push the patch I made but since I couldn't replicate your issue I'm not certain it fixed it :/

It does fix a minor annoyance with spaces before words slightly changing how the words are shown so it should hopefully fix everything

Please reopen this issue if you still notice some issues!
